---
- name: "System | MacOSX | Update Homebrew"
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: "System | MacOSX | Install Homebrew Packages"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - jq

- name: "System | MacOSX | Enable Passwordless Sudo"
  community.general.sudoers:
    name: "{{ ansible_env['USER'] }}"
    user: "{{ ansible_env['USER'] }}"
    nopassword: true
    commands: ALL
    state: present
  become: true
